function listenerShowErrorDialog(obj, src, evtData)
% listenerShowErrorDialog(obj, src, evtData)
% Listener callback to show the error dialog
% executed upon catch of MibModel->"DatasetsPanelUpdate" event
%
% Parameters:
% src: handle to MibModel
% evtData: event data, an instance of core.ToggleEventData class with the following fields:
% .Parameters field containing a structure with the
%    .evtData.Parameters.winTitle - title for the dialog (default="Error")
%    .evtData.Parameters.optionalPrefix - char with the prefix text for the dialog
%    .evtData.Parameters.optionalSuffix - char with the suffix text for the dialog
%    .evtData.Parameters.guiHandle - handle of the parent window, by default the main MIB window (obj.view.gui) is used
%    .evtData.Parameters.err - a structure generated by MATLAB, when an error is triggered with the following fields,
%        .identifier - identificator of the error
%        .message - error message
%        .cause - MException
% .Source -> handle to MibModel
% .EventName -> string with the event name that triggered the callback
% see example in MibModel.datasetsSetsOps

arguments
    obj controllers.MibController
    src models.MibModel
    evtData event.EventData
end

% set default parameters
if ~isfield(evtData.Parameters, 'winTitle'); evtData.Parameters.winTitle = 'Error'; end
if ~isfield(evtData.Parameters, 'optionalPrefix'); evtData.Parameters.optionalPrefix = ''; end
if ~isfield(evtData.Parameters, 'optionalSuffix'); evtData.Parameters.optionalSuffix = ''; end
if ~isfield(evtData.Parameters, 'guiHandle'); evtData.Parameters.guiHandle = obj.view.gui; end
if ~isfield(evtData.Parameters, 'err'); evtData.Parameters.err = struct; end % a structure generated by MATLAB, when an error is triggered

utils.dlgs.showErrorDialog(evtData.Parameters.guiHandle, ...
    evtData.Parameters.err, ...
    evtData.Parameters.winTitle, ...
    evtData.Parameters.optionalPrefix, ...
    evtData.Parameters.optionalSuffix);

end