function listener_showErrorDialog(obj, src, evtData)
% listener_showErrorDialog(obj, src, evtData)
% Listener callback to show the error dialog
% executed upon catch of MibModel->"DatasetsPanelUpdate" event
%
% Parameters:
% src: handle to MibModel
% evtData: event data, an instance of core.ToggleEventData class with the following fields:
% .Parameters field containing a structure with the
%    .evtData.Parameters.winTitle - title for the dialog (default="Error")
%    .evtData.Parameters.optionalPrefix - char with the prefix text for the dialog
%    .evtData.Parameters.optionalSuffix - char with the suffix text for the dialog
%    .evtData.Parameters.guiHandle - handle of the parent window, by default the main MIB window (obj.view.gui) is used
%    .evtData.Parameters.err - a structure generated by MATLAB, when an error is triggered with the following fields,
%        .identifier - identificator of the error
%        .message - error message
%        .cause - MException
%    .evtData.WindowHeight - number with the height of the dialog
% .Source -> handle to MibModel
% .EventName -> string with the event name that triggered the callback
% see example in MibModel.datasetsSetsOps
%
% Example:
% ErrorDlgOpt.winTitle = 'Error in MibModel.datasetsSetsOps';
% ErrorDlgOpt.optionalPrefix = sprintf('!!! Ops !!!\n\nThe last set can not be removed!');
% ErrorDlgOpt.err = 'Error text!';
% ErrorDlgOpt.WindowHeight = 150;
% eventdata = core.ToggleEventData(ErrorDlgOpt);
% notify(obj, 'ShowErrorDialog', eventdata); % typically used from mibModel

arguments
    obj controllers.MibController
    src models.MibModel
    evtData event.EventData
end

% set default parameters
if ~isfield(evtData.Parameters, 'winTitle'); evtData.Parameters.winTitle = 'Error'; end
if ~isfield(evtData.Parameters, 'optionalPrefix'); evtData.Parameters.optionalPrefix = ''; end
if ~isfield(evtData.Parameters, 'optionalSuffix'); evtData.Parameters.optionalSuffix = ''; end
if ~isfield(evtData.Parameters, 'guiHandle'); evtData.Parameters.guiHandle = obj.view.gui; end
if ~isfield(evtData.Parameters, 'err'); evtData.Parameters.err = struct; end % a structure generated by MATLAB, when an error is triggered

errorOpts.mibPath = obj.mibModel.mibPath;
if isfield(evtData.Parameters, 'WindowHeight'); errorOpts.WindowHeight = evtData.Parameters.WindowHeight; end
utils.dlgs.showErrorDialog(evtData.Parameters.guiHandle, ...
    evtData.Parameters.err, evtData.Parameters.winTitle, ...
    evtData.Parameters.optionalPrefix, ...
    evtData.Parameters.optionalSuffix, errorOpts);

end