function listenerShowErrorDialog(obj, src, evtData)
% listenerShowErrorDialog(obj, src, evtData)
% Listener callback to show the error dialog
%
% Parameters:
% src: handle to MibModel
% evtData: event data, an instance of core.ToggleEventData class with the following fields:
% .Parameters field containing a structure with the
%    .evtData.Parameter.winTitle - title for the dialog (default="Error")
%    .evtData.Parameter.optionalPrefix - char with the prefix text for the dialog
%    .evtData.Parameter.optionalSuffix - char with the suffix text for the dialog
%    .evtData.Parameter.guiHandle - handle of the parent window, by default the main MIB window (obj.view.gui) is used
%    .evtData.Parameter.err - a structure generated by MATLAB, when an error is triggered with the following fields,
%        .identifier - identificator of the error
%        .message - error message
%        .cause - MException
% .Source -> handle to MibModel
% .EventName -> string with the event name that triggered the callback
% see example in MibModel.datasetsSetsOps

arguments
    obj controllers.MibController
    src models.MibModel
    evtData event.EventData
end

% set default parameters
if ~isfield(evtData.Parameter, 'winTitle'); evtData.Parameter.winTitle = 'Error'; end
if ~isfield(evtData.Parameter, 'optionalPrefix'); evtData.Parameter.optionalPrefix = ''; end
if ~isfield(evtData.Parameter, 'optionalSuffix'); evtData.Parameter.optionalSuffix = ''; end
if ~isfield(evtData.Parameter, 'guiHandle'); evtData.Parameter.guiHandle = obj.view.gui; end
if ~isfield(evtData.Parameter, 'err'); evtData.Parameter.err = struct; end % a structure generated by MATLAB, when an error is triggered

utils.dlgs.showErrorDialog(evtData.Parameter.guiHandle, ...
    evtData.Parameter.err, ...
    evtData.Parameter.winTitle, ...
    evtData.Parameter.optionalPrefix, ...
    evtData.Parameter.optionalSuffix);

end