function listener_showErrorDialog(obj, src, evtData)
% LISTENER_SHOWERRORDIALOG - Listener callback to show the error dialog.
%
% Syntax:
%   .. code-block:: matlab
%
%      obj.listener_showErrorDialog(src, evtData)
%
% Executed upon catch of MibModel ``ShowErrorDialog`` event.
%
% Input Arguments:
%   - **src** — handle to MibModel
%   - **evtData** — event data; ``evtData.Parameters`` is a structure with the following fields:
%
%     - ``.winTitle`` — title for the dialog (default: ``'Error'``)
%     - ``.optionalPrefix`` — char with the prefix text for the dialog
%     - ``.optionalSuffix`` — char with the suffix text for the dialog
%     - ``.guiHandle`` — handle of the parent window (default: ``obj.view.gui``)
%     - ``.err`` — a structure generated by MATLAB when an error is triggered,
%       with ``.identifier``, ``.message``, ``.cause`` fields
%     - ``.WindowHeight`` — *(optional)* height of the dialog in pixels
%
% Output Arguments:
%   (none)
%
% **Example** — fire a ShowErrorDialog event from MibModel:
%
%   .. code-block:: matlab
%
%      ErrorDlgOpt.winTitle = 'Error in MibModel.datasetsSetsOps';
%      ErrorDlgOpt.optionalPrefix = sprintf('!!! Ops !!!\n\nThe last set can not be removed!');
%      ErrorDlgOpt.err = 'Error text!';
%      ErrorDlgOpt.WindowHeight = 150;
%      eventdata = core.ToggleEventData(ErrorDlgOpt);
%      notify(obj, 'ShowErrorDialog', eventdata);
%

arguments
    obj controllers.MibController
    src models.MibModel
    evtData event.EventData
end

% set default parameters
if ~isfield(evtData.Parameters, 'winTitle'); evtData.Parameters.winTitle = 'Error'; end
if ~isfield(evtData.Parameters, 'optionalPrefix'); evtData.Parameters.optionalPrefix = ''; end
if ~isfield(evtData.Parameters, 'optionalSuffix'); evtData.Parameters.optionalSuffix = ''; end
if ~isfield(evtData.Parameters, 'guiHandle'); evtData.Parameters.guiHandle = obj.view.gui; end
if ~isfield(evtData.Parameters, 'err'); evtData.Parameters.err = struct; end % a structure generated by MATLAB, when an error is triggered

errorOpts.mibPath = obj.mibModel.mibPath;
if isfield(evtData.Parameters, 'WindowHeight'); errorOpts.WindowHeight = evtData.Parameters.WindowHeight; end
utils.dlgs.showErrorDialog(evtData.Parameters.guiHandle, ...
    evtData.Parameters.err, evtData.Parameters.winTitle, ...
    evtData.Parameters.optionalPrefix, ...
    evtData.Parameters.optionalSuffix, errorOpts);

end
