function status = loadLayout(obj, mode, layoutFilename)
% LOADLAYOUT - Restore MIB layout from a JSON file.
%
% Syntax:
%   .. code-block:: matlab
%
%      status = obj.loadLayout()
%      status = obj.loadLayout(mode)
%      status = obj.loadLayout(mode, layoutFilename)
%
% Input Arguments:
%   - **mode** - *(optional)* char, default: ``'localDefault'``
%
%     - ``'localDefault'`` - restore the local default layout from ``utils.getPrefDir/mibDefaultLayout.json``
%     - ``'custom'`` - restore a custom layout from ``utils.getPrefDir``
%     - ``'globalDefault'`` - restore the bundled default layout from ``MIB/assets/defaultLayout.json``
%   - **layoutFilename** - *(optional)* char with the full path to a JSON layout file
%     generated by the ``saveLayout`` function
%
% Output Arguments:
%   - **status** - logical; ``true`` on success, ``false`` if layout could not be restored
%
% **Example 1** - restore the default layout:
%
%   .. code-block:: matlab
%
%      status = obj.loadLayout();
%
% **Example 2** - restore a custom layout from file:
%
%   .. code-block:: matlab
%
%      status = obj.loadLayout('custom', 'c:\temp\mibLayout.json');
%

%
% Updates
%

arguments (Input)
    obj controllers.MibController
    mode (1,:) char = 'custom'
    layoutFilename (1,:) char = ''
end

arguments (Output)
    status (1,1) logical
end

status = false;

switch mode
    case 'localDefault'
        % get the output path
        prefdir = utils.getPrefDir(); % get the directory with MIB preferences
        layoutFilename = fullfile(prefdir, 'mibDefaultLayout.json');
        
        if ~isfile(layoutFilename) % get default MIB layout
            layoutFilename = fullfile(obj.mibPath, 'assets', 'mibDefaultLayout.json'); 
        end
    case 'custom'
        if isempty(layoutFilename)
            prefdir = utils.getPrefDir(); % get the directory with MIB preferences
            [fileName, filePath] = uigetfile({'*.json', 'JSON format'; '*.*','All Files (*.*)'}, 'Select layout file', prefdir);
            if isequal(fileName, 0), return; end
            layoutFilename = fullfile(filePath, fileName); % construct the full file path
        end

        if ~isfile(layoutFilename)
            uialert(obj.view.gui, ...
                sprintf('!!! Error !!!\n\nThe custom layout file is missing!\n\nLocation of the selected custom layout file:\n%s', layoutFilename), ...
                'Missing MIB custom layout');
        end

    case 'globalDefault'
        layoutFilename = fullfile(obj.mibPath, 'assets', 'mibDefaultLayout.json'); 
        if ~isfile(layoutFilename)
            uialert(obj.view.gui, ...
                sprintf('!!! Error !!!\n\nThe default MIB layout is missing!\n\nLocation of the default MIB layout:\n%s', layoutFilename), ...
                'Missing MIB default layout');
        end
end

% Load the layout from the JSON file
layoutData = jsondecode(fileread(layoutFilename));

% Guard: if the saved layout was created before a panel was added, the
% children counts will differ - applying it would hide the new panel.
for position = {'left', 'right', 'bottom'}
    positionName = position{1};
    if isfield(obj.view.gui.PanelLayout, positionName)
        currentCount = numel(obj.view.gui.PanelLayout.(positionName).children);
        if isfield(layoutData.panelLayout, positionName)
            loadedCount = numel(layoutData.panelLayout.(positionName).children);
        else
            loadedCount = 0;
        end
        if currentCount ~= loadedCount
            status = false;
            return;
        end
    end
end

% Restore the layout using the loaded data
obj.view.gui.PanelLayout = layoutData.panelLayout;

status = true;
end
