function status = loadLayout(obj, mode, layoutFilename)
% LOADLAYOUT - Restore MIB layout from a JSON file.
%
% Syntax:
%   .. code-block:: matlab
%
%      status = obj.loadLayout()
%      status = obj.loadLayout(mode)
%      status = obj.loadLayout(mode, layoutFilename)
%
% Input Arguments:
%   - **mode** - *(optional)* char, default: ``'localDefault'``
%
%     - ``'localDefault'`` - restore the local default layout from ``utils.getPrefDir/mibDefaultLayout.json``
%     - ``'custom'`` - restore a custom layout from ``utils.getPrefDir``
%     - ``'globalDefault'`` - restore the bundled default layout from ``MIB/assets/defaultLayout.json``
%   - **layoutFilename** - *(optional)* char with the full path to a JSON layout file
%     generated by the ``saveLayout`` function
%
% Output Arguments:
%   - **status** - logical; ``true`` on success, ``false`` if layout could not be restored
%
% **Example 1** - restore the default layout:
%
%   .. code-block:: matlab
%
%      status = obj.loadLayout();
%
% **Example 2** - restore a custom layout from file:
%
%   .. code-block:: matlab
%
%      status = obj.loadLayout('custom', 'c:\temp\mibLayout.json');
%

%
% Updates
%

arguments (Input)
    obj controllers.MibController
    mode (1,:) char = 'custom'
    layoutFilename (1,:) char = ''
end

arguments (Output)
    status (1,1) logical
end

status = false;

switch mode
    case 'localDefault'
        % get the output path
        prefdir = utils.getPrefDir(); % get the directory with MIB preferences
        layoutFilename = fullfile(prefdir, 'mibDefaultLayout.json');
        
        if ~isfile(layoutFilename) % get default MIB layout
            layoutFilename = fullfile(obj.mibPath, 'assets', 'mibDefaultLayout.json'); 
        end
    case 'custom'
        if isempty(layoutFilename)
            prefdir = utils.getPrefDir(); % get the directory with MIB preferences
            [fileName, filePath] = uigetfile({'*.json', 'JSON format'; '*.*','All Files (*.*)'}, 'Select layout file', prefdir);
            if isequal(fileName, 0), return; end
            layoutFilename = fullfile(filePath, fileName); % construct the full file path
        end

        if ~isfile(layoutFilename)
            uialert(obj.view.gui, ...
                sprintf('!!! Error !!!\n\nThe custom layout file is missing!\n\nLocation of the selected custom layout file:\n%s', layoutFilename), ...
                'Missing MIB custom layout');
        end

    case 'globalDefault'
        layoutFilename = fullfile(obj.mibPath, 'assets', 'mibDefaultLayout.json'); 
        if ~isfile(layoutFilename)
            uialert(obj.view.gui, ...
                sprintf('!!! Error !!!\n\nThe default MIB layout is missing!\n\nLocation of the default MIB layout:\n%s', layoutFilename), ...
                'Missing MIB default layout');
        end
end

% Load the layout from the JSON file
layoutData = jsondecode(fileread(layoutFilename));

% Guard: compare the set of panel ids regardless of which side they are
% docked to, so a panel that was moved to a different side (left/right/
% bottom) since the layout was saved still restores correctly - only a
% genuine mismatch (a panel added or removed, e.g. after a MIB update)
% should block restoring, because applying it would hide the new panel or
% reference one that no longer exists.
currentIds = getPanelIds(obj.view.gui.PanelLayout);
if isfield(layoutData, 'panelLayout')
    loadedIds = getPanelIds(layoutData.panelLayout);
else
    loadedIds = {};
end

if ~isempty(setxor(currentIds, loadedIds))
    status = false;
    return;
end

% Restore the layout using the loaded data
obj.view.gui.PanelLayout = layoutData.panelLayout;

status = true;
end

function panelIds = getPanelIds(panelLayout)
% collect panel ids across all docking sides (left/right/bottom/top, ...)
% of a PanelLayout structure, irrespective of which side each is docked to
panelIds = {};
sideNames = fieldnames(panelLayout);
for sideIndex = 1:numel(sideNames)
    side = panelLayout.(sideNames{sideIndex});
    if isstruct(side) && isfield(side, 'children')
        children = side.children;
        % jsondecode returns a struct array when all children share the
        % same fields, but falls back to a cell array of structs when they
        % do not (e.g. only some panels have a "showing" field)
        if iscell(children)
            panelIds = [panelIds; cellfun(@(child) child.id, children, 'UniformOutput', false)]; %#ok<AGROW>
        else
            panelIds = [panelIds; {children.id}']; %#ok<AGROW>
        end
    end
end
end
