function showErrorDialog(guiHandle, err, winTitle, optionalPrefix, optionalSuffix)
% function showErrorDialog(guiHandle, err, winTitle, optionalPrefix, optionalSuffix)
% show error that is generated in try/catch blocks or in any other occasion
%
% Parameters:
% guiHandle: handle to appdesigner window (for example, obj.View.gui)
% err: a structure generated by MATLAB, when an error is
% triggered with the following fields,
%   .identifier - identificator of the error
%   .message - error message
%   .cause - MException
% winTitle: an optional string with a title for the window
% optionalPrefix: an optional text string that will be added before the end of the error message
% optionalSuffix: an optional text string that will be added after the end of the error message

%|
% @b Examples:
% @code
% try
% // some code
% catch err
%    utils.showErrorDialog(obj.view.gui, err, 'Missing net-variable'); //    when called from MibController
%    return;
% end
% @endcode
% @code
% ErrorDlgOpt.winTitle = 'Error in MibModel.datasetsSetsOps';
% ErrorDlgOpt.optionalPrefix = sprintf('!!! Warning !!!\n\nThe last set can not be removed!');
% eventdata = core.ToggleEventData(ErrorDlgOpt);
% notify(obj, 'ShowErrorDialog', eventdata);
% @endcode

% Updates
% 

if nargin < 5; optionalSuffix = ''; end
if nargin < 4; optionalPrefix = ''; end
if nargin < 3; winTitle = 'Error'; end

% generate error string
if isempty(fields(err))
    errText = sprintf('%s\n%s', optionalPrefix, optionalSuffix);
elseif ~isempty(err.cause)
    cause = err.cause{1}.message;
    errText = sprintf('!!! Error !!!\n\n%s\n%s\n\n%s\n\n%s\n\n%s', optionalPrefix, err.identifier, err.message, cause, optionalSuffix);
else
    errText = sprintf('!!! Error !!!\n\n%s\n%s\n\n%s\n\n%s', optionalPrefix, err.identifier, err.message, optionalSuffix);
end

if isempty(guiHandle) || isa(guiHandle, 'matlab.ui.Figure') % guide figure
    errordlg(errText, winTitle);
else                                                        % appdesigner figure
    uialert(guiHandle, ...
        errText, ...
        winTitle, 'Icon', 'error', 'Interpreter', 'html');
end
end