function out = matReadInstanceLabels(filename, getImageOptions)
% MATREADINSTANCELABELS - Read preprocessed instance-segmentation labels from a MAT file
% and return them as a cell array.
%
% Syntax:
%   .. code-block:: matlab
%
%      out = matReadInstanceLabels(filename, getImageOptions)
%
% Input Arguments:
%   - **filename** — [string] full path to the MAT file containing three variables:
%
%     - ``instanceBoxes`` — ``[N×4 double]`` bounding-box coordinates (one row per object)
%     - ``instanceNames`` — ``[N×1 categorical]`` object class labels
%     - ``instanceMasks`` — ``[H×W×N logical]`` binary mask stack (one slice per object)
%
%   - **getImageOptions** — struct passed to ``deepmib.storeLoadImages``
%     for loading the corresponding image file; see that function for field details
%
% Output Arguments:
%   - **out** — cell array:
%
%     - ``out{1}`` — loaded image (grayscale converted to RGB)
%     - ``out{2}`` — ``instanceBoxes`` matrix
%     - ``out{3}`` — ``instanceNames`` categorical array
%     - ``out{4}`` — ``instanceMasks`` logical stack
%


% read 3 variables that were generated by preprocessing the instance labels
% model: instanceBoxes, instanceNames, instanceMasks
data = load(filename);

% generate path to an image that corresponds to the instance mask
[projectDir, parentDir] = fileparts(fileparts(filename));

if parentDir(1) == 'T'  % image coming for training
    imageFilename = fullfile(projectDir, 'TrainImages', data.imageFilename);
else                    % image coming for validation
    imageFilename = fullfile(projectDir, 'ValidationImages', data.imageFilename);
end
% storeLoadImages returns a 5D array [height width depth colors time];
% for a 2D instance image squeeze away the singleton depth/time dimensions
out{1} = squeeze(deepmib.storeLoadImages(imageFilename, getImageOptions));
if ndims(out{1}) > 3
    errordlg(sprintf(['!!! Error !!!\n\n' ...
                    'The instance segmentation requires 2D images:\n' ...
                    'width x height x colors,\n' ...
                    'where colors can be 1 or 3 channel images']),...
            'Preprocessing instances', 'modal');
    return;
end
% convert Grayscale to RGB
if size(out{1}, 3) == 1
    out{1} = repmat(out{1}, [1, 1, 3]);
end

out{2} = data.instanceBoxes;       % Nx4 double bounding boxes
%out{3} = repmat(categorical("Object"), [numObjects 1]);       % Nx1 categorical object labels
out{3} = data.instanceNames;
out{4} = data.instanceMasks;        % HxWxN logical mask arrays

