site_name: Microscopy Image Browser documentation
site_url: https://mib.helsinki.fi
extra_css:    # location for additional css styles
  - css/styles.css  # Relative to the docs/ directory
  #- css/style_tests.css  # Relative to the docs/ directory for testing styles
extra_javascript:   # location for additional javascript files
  - css/extra.js

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono # Roboto Mono
  logo: assets/mib_icon.png   # logo for the top left corner
  favicon: assets/mib_icon.png   # icon for browser tab

  features:
    - content.code.copy   # add copy button to the code blocks
    - navigation.top      # add back to top button
    - navigation.instant.progress     # progress indicator at the top of the page and will be hidden once the page has fully loaded
    #- navigation.tracking     # When anchor tracking is enabled, the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents.
    #- navigation.tabs       # top-level sections are rendered in a menu layer below the header for viewports above 1220px, but remain as-is on mobile
    #- navigation.tabs.sticky # make the tabs sticky
    - navigation.sections     # When sections are enabled, top-level sections are rendered as groups in the sidebar for viewports above 1220px, but remain as-is on mobile.
    #- navigation.expand       # When expansion is enabled, the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually.
    #- navigation.prune        # [not compatible with navigation.expand] When pruning is enabled, only the visible navigation items are included in the rendered HTML, reducing the size of the built site by 33% or more
    - navigation.path       # When navigation paths are activated, a breadcrumb navigation is rendered above the title of each page, which might make orientation easier for users visiting your documentation on devices with smaller screens.
    - navigation.indexes    # When section index pages are enabled, documents can be directly attached to sections, which is particularly useful for providing overview pages.
    - content.footnote.tooltips   # add tooltips [^1]
    - content.tooltips        # add tooltips
    - content.images.lightbox  # Enable lightbox for images
    # - navigation.footer      # add footer with navigation
    - search.suggest        # add search suggestions
    - header.autohide       # autohide header after certain threshold

  icon:
    annotation: material/chevron-right-circle   # icon for annotations

  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green   # primary color
      accent: orange    # color for highlighting links

    # Light mode
    - scheme: default   # default -> white, slate->black
      toggle:
        icon: material/weather-night
        name: Dark mode
      # primary: green #'#F28C38'  # primary color, overridden in styles.css [data-md-color-scheme="bright"]
      # accent: '#2E6B47'   # color for highlighting links, https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

extra:
  homepage: https://mib.helsinki.fi/help/main2/   # link that is activated upon press on logo
  social:
    - icon: fontawesome/solid/house-chimney
      link: https://mib.helsinki.fi
    - icon: fontawesome/brands/github         # bundled icons location: site-packages\material\templates\.icons
      link: https://github.com/Ajaxels/MIB3


copyright: Copyright &copy; 2010 - 2025 Ilya Belevich

nav:
  - Microscopy Image Browser: index.md
  - Getting Started:
      - getting-started/index.md  # Overview page for Getting Started
      - Installation:
          - getting-started/installation/index.md
      - Features: https://mib.helsinki.fi/features_all.html
      - Tutorials:
          - getting-started/tutorials/index.md
      - Acknowledgements: getting-started/acknowledgements.md
      - Licenses:
          - getting-started/licenses/index.md
          - MIB for MATLAB: getting-started/licenses/license-mib-matlab.md
          - MIB standalone: getting-started/licenses/license-mib-standalone.md
          - External licenses: getting-started/licenses/licenses-ext.md
      - Contact and Support: getting-started/support.md
      - Release notes:
          - getting-started/releasenotes/index.md
          - History:  getting-started/releasenotes/release-notes-history.md
  - User interface:
      - user-interface/index.md
      - Ribbon:
          - user-interface/ribbon/index.md
          - Home:
            - user-interface/ribbon/home/index.md
            - Batch processing: user-interface/ribbon/home/home-batchprocessing.md
            - Chopped images: user-interface/ribbon/home/home-choppedimages.md
            - Rename and shuffle: user-interface/ribbon/home/home-renameandshuffle.md
            - Make video: user-interface/ribbon/home/home-makevideo.md
            - Make snapshot: user-interface/ribbon/home/home-makesnapshot.md
            - MIB 3D Viewer: user-interface/ribbon/home/home-mib3Dviewer.md
            - Preferences: user-interface/ribbon/home/home-preferences.md
          - Dataset:
            - user-interface/ribbon/dataset/index.md
            - Alignment tool: user-interface/ribbon/dataset/dataset-alignment.md
            - Crop: user-interface/ribbon/dataset/dataset-crop.md
            - Resample: user-interface/ribbon/dataset/dataset-resample.md
            - Transform: user-interface/ribbon/dataset/dataset-transform.md
            - Slice: user-interface/ribbon/dataset/dataset-slice.md
            - Bounding box: user-interface/ribbon/dataset/dataset-bb.md
          - Image:
            - user-interface/ribbon/image/index.md
            - Image filters: user-interface/ribbon/image/image-filters.md
            - -> content aware fill: user-interface/ribbon/image/image-tools-awarefill.md
            - -> debris removal: user-interface/ribbon/image/image-tools-debris.md
            - -> image arithmetics: user-interface/ribbon/image/image-tools-arithmetic.md
            - -> intensity projection: user-interface/ribbon/image/image-tools-projections.md
            - -> select image frame: user-interface/ribbon/image/image-tools-selectframe.md
            - -> white balance correction: user-interface/ribbon/image/image-tools-whitebalance.md
            - Morphological ops: user-interface/ribbon/image/image-morphops.md
          - Model:
            - user-interface/ribbon/model/index.md
            - Statistics: user-interface/ribbon/mask/mask-stats.md
          - Mask:
            - user-interface/ribbon/mask/index.md
            - Statistics: user-interface/ribbon/mask/mask-stats.md
          - Selection:
            - user-interface/ribbon/selection/index.md
            - Morphological ops: user-interface/ribbon/selection/selection-morphops.md
          - Tools:
            - user-interface/ribbon/tools/index.md
            - Deep learning: user-interface/deepmib/index.md
            - Global thresholding: user-interface/ribbon/tools/tools-globalthres.md
            - Graphcut: user-interface/ribbon/tools/tools-graphcut.md
            - Measure tool: user-interface/ribbon/tools/tools-measuretool.md
            - Object separation: user-interface/ribbon/tools/tools-objectsep.md
            - Random forest classifier: user-interface/ribbon/tools/tools-randforest.md
            - Random forest superpixels: user-interface/ribbon/tools/tools-randforest-slic.md
            - Stereology: user-interface/ribbon/tools/tools-stereology.md
            - Watershed: user-interface/ribbon/tools/tools-watershed.md
            - Wound healing assay: user-interface/ribbon/tools/tools-wound.md
          - Plugins: user-interface/plugins/index.md
          - Help:
            - user-interface/ribbon/help/index.md
      - Quick Access Bar:
          - user-interface/quick-access-bar/index.md
      - Panels:
          - user-interface/panels/index.md
          - Path:
            - user-interface/panels/path/index.md
          - Directory contents:
            - user-interface/panels/dircontents/index.md
          - Segmentation:
            - user-interface/panels/segm/index.md
            - 3D ball: user-interface/panels/segm/segm-3dball.md
            - 3D lines: user-interface/panels/segm/segm-3dlines.md
            - Annotations: user-interface/panels/segm/segm-annotations.md
            - Brush: user-interface/panels/segm/segm-brush.md
            - BW Thresholding: user-interface/panels/segm/segm-bwthres.md
            - Drag & Drop materials: user-interface/panels/segm/segm-dragdrop.md
            - Lasso: user-interface/panels/segm/segm-lasso.md
            - MagicWand-RegionGrowing: user-interface/panels/segm/segm-magicwand.md
            - Membrane ClickTracker: user-interface/panels/segm/segm-membrtracker.md
            - Object Picker: user-interface/panels/segm/segm-objpick.md
            - Segment Anything Model: user-interface/panels/segm/segm-sam.md
            - Spot: user-interface/panels/segm/segm-spot.md
          - Image view:
            - user-interface/panels/imview/index.md
          - Selection:
            - user-interface/panels/selection/index.md
          - View settings:
            - user-interface/panels/viewsettings/index.md
            - Image adjustment: user-interface/panels/viewsettings/viewsettings-adjustments.md
          - Image filters:
            - user-interface/panels/imfilters/index.md
          - ROIs:
            - user-interface/panels/roi/index.md
          - Mask generators:
            - user-interface/panels/maskgen/index.md
          - Fiji connect:
            - user-interface/panels/fijiconnect/index.md
      - Segmentation tools:
          - 3D ball: user-interface/panels/segm/segm-3dball.md
          - 3D lines: user-interface/panels/segm/segm-3dlines.md
          - Annotations: user-interface/panels/segm/segm-annotations.md
          - Brush: user-interface/panels/segm/segm-brush.md
          - BW Thresholding: user-interface/panels/segm/segm-bwthres.md
          - Deep learning: user-interface/deepmib/deepmib-networks.md
          - Drag & Drop materials: user-interface/panels/segm/segm-dragdrop.md
          - Graphcut: user-interface/ribbon/tools/tools-graphcut.md
          - Lasso: user-interface/panels/segm/segm-lasso.md
          - MagicWand-RegionGrowing: user-interface/panels/segm/segm-magicwand.md
          - Membrane ClickTracker: user-interface/panels/segm/segm-membrtracker.md
          - Object Picker: user-interface/panels/segm/segm-objpick.md
          - Segment Anything Model: user-interface/panels/segm/segm-sam.md
          - Spot: user-interface/panels/segm/segm-spot.md
      - Plugins:
        - user-interface/plugins/index.md
        - File processing:
            - user-interface/plugins/file-processing/index.md
            - Image converter: user-interface/plugins/file-processing/image-converter.md
            - Multi rename tool: user-interface/plugins/file-processing/multi-rename-tool.md
        - Intensity analysis:
            - user-interface/plugins/intensity-analysis/index.md
            - Triple area intensity: user-interface/plugins/intensity-analysis/triple-area-intensity.md
        - Organelle analysis:
            - user-interface/plugins/organelle-analysis/index.md
            - Granularity: user-interface/plugins/organelle-analysis/granularity.md
            - MCcalc: user-interface/plugins/organelle-analysis/mccalc.md
            - Surface area 3d: user-interface/plugins/organelle-analysis/surface-area-3d.md
            - Thres analysis for objects: user-interface/plugins/organelle-analysis/thres-analysis-for-objects.md
        - Plasmodesmata:
            - user-interface/plugins/plasmodesmata/index.md
            - Cell wall thickness: user-interface/plugins/plasmodesmata/cellwall-thickness.md
            - Spacial control points: user-interface/plugins/plasmodesmata/spacial-control-points.md
        - Tutorials:
            - user-interface/plugins/tutorials/index.md
            - GUI Tutorial: user-interface/plugins/tutorials/gui-tutorial.md
            - MIB App Design plugin: user-interface/plugins/tutorials/mib-app-design-plugin.md
            - MIB Plugin: user-interface/plugins/tutorials/mib-plugin.md
            - MIB Plugin withing GUI: user-interface/plugins/tutorials/mib-plugin-without-gui.md
      - DeepMIB:
          - user-interface/deepmib/index.md
          - Networks: user-interface/deepmib/deepmib-networks.md
          - Dirs: user-interface/deepmib/deepmib-dirs.md
          - Train: user-interface/deepmib/deepmib-train.md
          - Predict: user-interface/deepmib/deepmib-predict.md
          - Options: user-interface/deepmib/deepmib-options.md
      - Key and mouse shortcuts: user-interface/key-and-mouse-shortcuts.md
      - Image layers: user-interface/image-layers.md
  - Markdown: Markdown.md
  - Markdown examples: Markdown_examples.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:       # to enable use of icons and emoji inline as :octicons-gear-16:
      emoji_index: !!python/name:material.extensions.emoji.twemoji      # to enable use of icons and emoji inline as :octicons-gear-16:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg   # to enable use of icons and emoji inline as :octicons-gear-16:
  - pymdownx.highlight:   # enable highlighting of the code: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
      anchor_linenums: true   # Requires to add "~~~matlab"  in front of the code block
      line_spans: __span      # or "~~~py" in front of the code block for python
      pygments_lang_class: true   # https://pygments.org/docs/lexers/
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:              # add tabs,
      alternate_style: true       # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=tabbed#tabbed
  - pymdownx.keys                 # enable keys, https://facelessuser.github.io/pymdown-extensions/extensions/keys/#extendingmodifying-key-map-index
  - pymdownx.caret                # enable caret to make subscripts H~2~O and super scripts: https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.tilde                # and superscripts A^T^A
  - admonition                    # info boxes
  - pymdownx.details              # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admonitions
  - pymdownx.superfences
  - tables                        # add tables: https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - footnotes                     # add footnotes and tooltips: https://squidfunk.github.io/mkdocs-material/reference/footnotes/#fn:1
  - md_in_html                    # grid cards, images https://squidfunk.github.io/mkdocs-material/reference/grids/
  - pymdownx.blocks.caption       # for caption alignment
  - def_list                      # Definition Lists: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#definition-lists
  - pymdownx.tasklist:          # task lists https://squidfunk.github.io/mkdocs-material/reference/lists/#using-task-lists
      custom_checkbox: true

plugins:
  - glightbox:                    # add image zoom functionality, https://squidfunk.github.io/mkdocs-material/reference/images/ requires "pip install mkdocs-glightbox"
      effect: none                # Name of the effect on lightbox open. (zoom, fade, none)
      zoomable: true              # Enable or disable zoomable images
      skip_classes:               # Disable lightbox of those image with specific custom class name
        - skip-lightbox           # do not use lightbox, requires {.off-glb  } tag after the image
      manual: true                # require to use {on-glb} to show lightbox
      background: none            # The background CSS of lightbox image. The background will shown when the image is transparent. You can use any CSS value for the background for example #74b9ff or Gainsboro or none for nothing.
      shadow: false               # Enable or disable the shadow of lightbox image. Disable it when the background is none to prevent shadow around the transparent image.
      touchNavigation: true       # Enable or disable the touch navigation (swipe).
      loop: false                 # Loop slides on end
      slide_effect: fade          # Name of the effect on lightbox slide. (slide, zoom, fade, none)
      width: 100%                 # Width for inline elements and iframes. You can use any unit for example 90% or 100vw for full width.
      height: auto                # Height for inline elements and iframes. You can use any unit for example 90%, 100vh or auto
      draggable: false            # Enable or disable mouse drag to go prev and next slide.
      auto_caption: true         # Enable or disable using alt of image as caption title automatically.
      caption_position: bottom    # Default captions position. (bottom, top, left, right)
  - search                         # add Search
  - offline                       # The built-in offline plugin makes sure that the site search works when you distribute the contents of your site directory as a download
